### ISSUE TITLE
GetIdToken meethod has error

### ISSUE THREAD

**Issue by 6388qwe0** [dandar3/android-google-play-services-base#1]
```
09-19 19:49:57.186: E/TokenFragment(27375): Exception getting access token
09-19 19:49:57.186: E/TokenFragment(27375): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/auth/GoogleAuthUtil;
09-19 19:49:57.186: E/TokenFragment(27375):     at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:240)
09-19 19:49:57.186: E/TokenFragment(27375):     at com.google.games.bridge.TokenFragment$1.doInBackground(TokenFragment.java:211)
09-19 19:49:57.186: E/TokenFragment(27375):     at android.os.AsyncTask$2.call(AsyncTask.java:307)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-19 19:49:57.186: E/TokenFragment(27375):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.lang.Thread.run(Thread.java:833)
09-19 19:49:57.186: E/TokenFragment(27375): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.auth.GoogleAuthUtil" on path: DexPathList[[zip file "/data/app/com.yyj.xinrui-2/base.apk"],nativeLibraryDirectories=[/data/app/com.yyj.xinrui-2/lib/arm, /data/app/com.yyj.xinrui-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
09-19 19:49:57.186: E/TokenFragment(27375):     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-19 19:49:57.186: E/TokenFragment(27375):     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-19 19:49:57.186: E/TokenFragment(27375):     ... 8 more

```

**Comment by dandar3** [comment]
`com.google.android.gms.auth.GoogleAuthUtil` seems to be part of **Google Account Login** (`play-services-auth-base` library), which is not available here yet.

I will create the project later on today and will let you know.

**Comment by dandar3** [comment]
Check out the two new projects below:
- https://github.com/dandar3/android-google-play-services-auth/tree/9.4.0
- https://github.com/dandar3/android-google-play-services-auth-base/tree/9.4.0

**Comment by dandar3** [comment]
Any update?
